# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := ECE5465_Project3


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += ./WIZnet_Library/WIZnetInterface/DHCPClient/DHCPClient.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/DNSClient/DNSClient.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/Socket/Endpoint.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/Socket/Socket.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/Socket/TCPSocketConnection.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/Socket/TCPSocketServer.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/Socket/UDPSocket.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/WIZnet/W5100.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/WIZnet/W5200.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/WIZnet/W5500.o
OBJECTS += ./WIZnet_Library/WIZnetInterface/WIZnetInterface.o
OBJECTS += ./main.o
OBJECTS += ./mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += ./mbed-os/cmsis/TARGET_CORTEX_M/mbed_fault_handler.o
OBJECTS += ./mbed-os/cmsis/TARGET_CORTEX_M/mbed_tz_context.o
OBJECTS += ./mbed-os/components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.o
OBJECTS += ./mbed-os/components/802.15.4_RF/atmel-rf-driver/source/at24mac.o
OBJECTS += ./mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.o
OBJECTS += ./mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.o
OBJECTS += ./mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.o
OBJECTS += ./mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.o
OBJECTS += ./mbed-os/components/wifi/esp8266-driver/ESP8266/ESP8266.o
OBJECTS += ./mbed-os/components/wifi/esp8266-driver/ESP8266Interface.o
OBJECTS += ./mbed-os/drivers/AnalogIn.o
OBJECTS += ./mbed-os/drivers/BusIn.o
OBJECTS += ./mbed-os/drivers/BusInOut.o
OBJECTS += ./mbed-os/drivers/BusOut.o
OBJECTS += ./mbed-os/drivers/CAN.o
OBJECTS += ./mbed-os/drivers/Ethernet.o
OBJECTS += ./mbed-os/drivers/FlashIAP.o
OBJECTS += ./mbed-os/drivers/I2C.o
OBJECTS += ./mbed-os/drivers/I2CSlave.o
OBJECTS += ./mbed-os/drivers/InterruptIn.o
OBJECTS += ./mbed-os/drivers/InterruptManager.o
OBJECTS += ./mbed-os/drivers/MbedCRC.o
OBJECTS += ./mbed-os/drivers/QSPI.o
OBJECTS += ./mbed-os/drivers/RawSerial.o
OBJECTS += ./mbed-os/drivers/SPI.o
OBJECTS += ./mbed-os/drivers/SPISlave.o
OBJECTS += ./mbed-os/drivers/Serial.o
OBJECTS += ./mbed-os/drivers/SerialBase.o
OBJECTS += ./mbed-os/drivers/TableCRC.o
OBJECTS += ./mbed-os/drivers/Ticker.o
OBJECTS += ./mbed-os/drivers/Timeout.o
OBJECTS += ./mbed-os/drivers/Timer.o
OBJECTS += ./mbed-os/drivers/TimerEvent.o
OBJECTS += ./mbed-os/drivers/UARTSerial.o
OBJECTS += ./mbed-os/events/EventQueue.o
OBJECTS += ./mbed-os/events/equeue/equeue.o
OBJECTS += ./mbed-os/events/equeue/equeue_mbed.o
OBJECTS += ./mbed-os/events/equeue/equeue_posix.o
OBJECTS += ./mbed-os/events/mbed_shared_queues.o
OBJECTS += ./mbed-os/hal/LowPowerTickerWrapper.o
OBJECTS += ./mbed-os/hal/mbed_critical_section_api.o
OBJECTS += ./mbed-os/hal/mbed_flash_api.o
OBJECTS += ./mbed-os/hal/mbed_gpio.o
OBJECTS += ./mbed-os/hal/mbed_itm_api.o
OBJECTS += ./mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_lp_ticker_wrapper.o
OBJECTS += ./mbed-os/hal/mbed_pinmap_common.o
OBJECTS += ./mbed-os/hal/mbed_sleep_manager.o
OBJECTS += ./mbed-os/hal/mbed_ticker_api.o
OBJECTS += ./mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v7m.o
OBJECTS += ./mbed-os/hal/mpu/mbed_mpu_v8m.o
OBJECTS += ./mbed-os/platform/ATCmdParser.o
OBJECTS += ./mbed-os/platform/CThunkBase.o
OBJECTS += ./mbed-os/platform/CallChain.o
OBJECTS += ./mbed-os/platform/FileBase.o
OBJECTS += ./mbed-os/platform/FileHandle.o
OBJECTS += ./mbed-os/platform/FilePath.o
OBJECTS += ./mbed-os/platform/FileSystemHandle.o
OBJECTS += ./mbed-os/platform/LocalFileSystem.o
OBJECTS += ./mbed-os/platform/Stream.o
OBJECTS += ./mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += ./mbed-os/platform/mbed_application.o
OBJECTS += ./mbed-os/platform/mbed_assert.o
OBJECTS += ./mbed-os/platform/mbed_board.o
OBJECTS += ./mbed-os/platform/mbed_critical.o
OBJECTS += ./mbed-os/platform/mbed_error.o
OBJECTS += ./mbed-os/platform/mbed_error_hist.o
OBJECTS += ./mbed-os/platform/mbed_interface.o
OBJECTS += ./mbed-os/platform/mbed_mem_trace.o
OBJECTS += ./mbed-os/platform/mbed_mktime.o
OBJECTS += ./mbed-os/platform/mbed_mpu_mgmt.o
OBJECTS += ./mbed-os/platform/mbed_poll.o
OBJECTS += ./mbed-os/platform/mbed_retarget.o
OBJECTS += ./mbed-os/platform/mbed_rtc_time.o
OBJECTS += ./mbed-os/platform/mbed_sdk_boot.o
OBJECTS += ./mbed-os/platform/mbed_semihost_api.o
OBJECTS += ./mbed-os/platform/mbed_stats.o
OBJECTS += ./mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += ./mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += ./mbed-os/rtos/ConditionVariable.o
OBJECTS += ./mbed-os/rtos/EventFlags.o
OBJECTS += ./mbed-os/rtos/Kernel.o
OBJECTS += ./mbed-os/rtos/Mutex.o
OBJECTS += ./mbed-os/rtos/RtosTimer.o
OBJECTS += ./mbed-os/rtos/Semaphore.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/SysTimer.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_boot.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_rtos_rtx.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M0P/irq_cm0.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += ./mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += ./mbed-os/rtos/ThisThread.o
OBJECTS += ./mbed-os/rtos/Thread.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/PeripheralPins.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_ARM/startup_MKL25Z4.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/system_MKL25Z4.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/gpio_irq_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/mbed_overrides.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/serial_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/analogin_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/analogout_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/gpio_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/i2c_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/pinmap.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/port_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/pwmout_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/rtc_api.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/sleep.o
OBJECTS += ./mbed-os/targets/TARGET_Freescale/TARGET_KLXX/us_ticker.o


INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I.././WIZnet_Library
INCLUDE_PATHS += -I.././WIZnet_Library/WIZnetInterface
INCLUDE_PATHS += -I.././WIZnet_Library/WIZnetInterface/DHCPClient
INCLUDE_PATHS += -I.././WIZnet_Library/WIZnetInterface/DNSClient
INCLUDE_PATHS += -I.././WIZnet_Library/WIZnetInterface/Socket
INCLUDE_PATHS += -I.././WIZnet_Library/WIZnetInterface/WIZnet
INCLUDE_PATHS += -I.././mbed-os
INCLUDE_PATHS += -I.././mbed-os/cmsis
INCLUDE_PATHS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/components
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source
INCLUDE_PATHS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
INCLUDE_PATHS += -I.././mbed-os/components/wifi
INCLUDE_PATHS += -I.././mbed-os/components/wifi/esp8266-driver
INCLUDE_PATHS += -I.././mbed-os/components/wifi/esp8266-driver/ESP8266
INCLUDE_PATHS += -I.././mbed-os/drivers
INCLUDE_PATHS += -I.././mbed-os/events
INCLUDE_PATHS += -I.././mbed-os/events/equeue
INCLUDE_PATHS += -I.././mbed-os/hal
INCLUDE_PATHS += -I.././mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I.././mbed-os/platform
INCLUDE_PATHS += -I.././mbed-os/rtos
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_Freescale
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= .././mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_ARM/MKL25Z4.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m0plus -mthumb -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x20000 -DMBED_RAM_START=0x1ffff000 -DMBED_RAM_SIZE=0x4000 -DMBED_BOOT_STACK_SIZE=1024


C_FLAGS += -std=gnu99
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -D__MBED__=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DARM_MATH_CM0PLUS
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SEMIHOST=1
C_FLAGS += -DTARGET_M0P
C_FLAGS += -DTARGET_Freescale
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -D__CORTEX_M0PLUS
C_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
C_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
C_FLAGS += -DTARGET_KL25Z
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTARGET_KLXX
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DCOMPONENT_NSPE=1
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1554691890.8554902
C_FLAGS += -DTARGET_DEBUG
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -std=gnu99
C_FLAGS += -c
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -fno-builtin
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fno-delete-null-pointer-checks
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -O0
C_FLAGS += -g3
C_FLAGS += -DMBED_DEBUG
C_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
C_FLAGS += -mcpu=cortex-m0plus
C_FLAGS += -mthumb
C_FLAGS += -DMBED_ROM_START=0x0
C_FLAGS += -DMBED_ROM_SIZE=0x20000
C_FLAGS += -DMBED_RAM_START=0x1ffff000
C_FLAGS += -DMBED_RAM_SIZE=0x4000

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DARM_MATH_CM0PLUS
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SEMIHOST=1
CXX_FLAGS += -DTARGET_M0P
CXX_FLAGS += -DTARGET_Freescale
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -D__CORTEX_M0PLUS
CXX_FLAGS += -DCOMPONENT_PSA_SRV_EMUL=1
CXX_FLAGS += -DCOMPONENT_PSA_SRV_IMPL=1
CXX_FLAGS += -DTARGET_KL25Z
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTARGET_KLXX
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DCOMPONENT_NSPE=1
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1554691890.8554902
CXX_FLAGS += -DTARGET_DEBUG
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -c
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -fno-builtin
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fno-delete-null-pointer-checks
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -O0
CXX_FLAGS += -g3
CXX_FLAGS += -DMBED_DEBUG
CXX_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
CXX_FLAGS += -mcpu=cortex-m0plus
CXX_FLAGS += -mthumb
CXX_FLAGS += -DMBED_ROM_START=0x0
CXX_FLAGS += -DMBED_ROM_SIZE=0x20000
CXX_FLAGS += -DMBED_RAM_START=0x1ffff000
CXX_FLAGS += -DMBED_RAM_SIZE=0x4000

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__CORTEX_M0PLUS
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DARM_MATH_CM0PLUS
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -I../.
ASM_FLAGS += -I.././WIZnet_Library
ASM_FLAGS += -I.././WIZnet_Library/WIZnetInterface
ASM_FLAGS += -I.././WIZnet_Library/WIZnetInterface/DHCPClient
ASM_FLAGS += -I.././WIZnet_Library/WIZnetInterface/DNSClient
ASM_FLAGS += -I.././WIZnet_Library/WIZnetInterface/Socket
ASM_FLAGS += -I.././WIZnet_Library/WIZnetInterface/WIZnet
ASM_FLAGS += -I.././mbed-os
ASM_FLAGS += -I.././mbed-os/cmsis
ASM_FLAGS += -I.././mbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I.././mbed-os/components
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/atmel-rf-driver/source
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source
ASM_FLAGS += -I.././mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
ASM_FLAGS += -I.././mbed-os/components/wifi
ASM_FLAGS += -I.././mbed-os/components/wifi/esp8266-driver
ASM_FLAGS += -I.././mbed-os/components/wifi/esp8266-driver/ESP8266
ASM_FLAGS += -I.././mbed-os/drivers
ASM_FLAGS += -I.././mbed-os/events
ASM_FLAGS += -I.././mbed-os/events/equeue
ASM_FLAGS += -I.././mbed-os/hal
ASM_FLAGS += -I.././mbed-os/hal/storage_abstraction
ASM_FLAGS += -I.././mbed-os/platform
ASM_FLAGS += -I.././mbed-os/rtos
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx4
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/Include
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
ASM_FLAGS += -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
ASM_FLAGS += -I.././mbed-os/targets/TARGET_Freescale
ASM_FLAGS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX
ASM_FLAGS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z
ASM_FLAGS += -I.././mbed-os/targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device
ASM_FLAGS += -include
ASM_FLAGS += ..\mbed_config.h
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -c
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -fno-builtin
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fno-delete-null-pointer-checks
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -O0
ASM_FLAGS += -g3
ASM_FLAGS += -DMBED_DEBUG
ASM_FLAGS += -DMBED_TRAP_ERRORS_ENABLED=1
ASM_FLAGS += -mcpu=cortex-m0plus
ASM_FLAGS += -mthumb


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m0plus -mthumb -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x20000 -DMBED_RAM_START=0x1ffff000 -DMBED_RAM_SIZE=0x4000 -DMBED_BOOT_STACK_SIZE=1024 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
